[ui]
font_size = 11
log_file = shippy.log
default_weight = 3

; This file is a development-friendly template.
; The app also bundles a copy inside the package for bootstrap.

[easypost]
apikey = YOUR_EASYPOST_API_KEY

[googlemaps]
apikey = YOUR_GOOGLE_MAPS_API_KEY

[return_address]
name = Inside Books Project
street1 = PO Box 301029
street2 =
city = Austin
state = Texas
zipcode = 78703
